version: "3"
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: "mysql:5.7"
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    ports:
      - "3306:3306"

  pma:
    image: "phpmyadmin/phpmyadmin:4.7.8-1"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: $MYSQL_PORT
      PMA_USER: $MYSQL_USERNAME
      PMA_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "$PMA_PORT:80"

  redis:
    image: "redis:5.0.4"
